#!/usr/bin/env python3
"""Compose Table 2 (paired contrasts) and the ungrounded case-study macros.

Reads generated/attribution_numbers.tex (macros produced by
build_attribution_numbers.py) and generated/counterfactual_inputs.json, and
writes
  generated/attribution_contrasts.tex   -- tabular body for Table 2
  generated/attribution_case.tex        -- macros for the ungrounded example
No statistics are recomputed here; every number is copied from the macros
or read directly from the frozen score export.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, 'generated')
NUM = os.path.join(GEN, 'attribution_numbers.tex')
INP = os.path.join(GEN, 'counterfactual_inputs.json')
OUT_TAB = os.path.join(GEN, 'attribution_contrasts.tex')
OUT_CASE = os.path.join(GEN, 'attribution_case.tex')
TAB1 = os.path.join(GEN, 'attribution_table.tex')
OUT_TAB1 = os.path.join(GEN, 'attribution_table_fmt.tex')


def num(x, nd=2):
    """Format a margin without losing a significant digit to rounding.

    '%.1f' turned the rival-removal margin 0.25 into 0.2 (binary 0.25 is an
    exact tie, and printf rounds it to even), contradicting the 0.25 quoted
    in the text. Keep up to nd decimals and drop trailing zeros.
    """
    s = ('%.*f' % (nd, round(float(x), nd))).rstrip('0').rstrip('.')
    return s if s not in ('', '-0') else '0'

# Illustrative competitor-confused answer used in Sec. 5 and Fig. 1(a). Chosen
# from the competitor-confused cases: target-removal effect clearly positive
# (passes the target-only check) yet the rival-removal effect is larger, so the
# target-absent view outscores a target-present view. Hand-selected for
# exposition; all values are read from the export below. Its three frozen
# rendered views are fetched from the experiment server into
# tmp/case_audio_creak/ (hashes verified against the manifest).
#
# The example uses Qwen3-Omni-30B, the most accurate model in Table 1 (84.3%),
# rather than the earlier Qwen2.5-Omni-7B+AHA. The failure is therefore not a
# weakness of one adapted 7B checkpoint: the strongest model in the panel
# exhibits it, and its ordering conflict is larger (H = -2.00 vs -1.31). The
# removal views depend only on the mixture and the deleted source, so the same
# cached audio serves this model; only the three scored margins change.
CASE_MODEL = 'qwen3_omni_30b'
CASE_MODEL_NAME = 'Qwen3-Omni-30B'
CASE_COND = 'esc50_0001_q2_snrp0_partial_d1r1'


def macros():
    m = {}
    for path in (NUM, os.path.join(GEN, 'revision_numbers.tex')):
        for line in open(path):
            r = re.match(r'\\newcommand\{\\(\w+)\}\{(.*)\}\s*$', line)
            if r:
                m[r.group(1)] = r.group(2)
    return m


def pct(s):
    return s.replace('\\%', '').replace('%', '')


def ci(s):
    # "10.4,\,14.0" -> "[10.4, 14.0]"
    return '[' + s.replace('\\,', ' ') + ']'


def sign(s):
    return s if s.startswith('-') else '+' + s


def main():
    m = macros()
    rows = [
        ('\\multicolumn{5}{l}{\\emph{Acoustic competition (common-correct units)}}\\\\',),
        ('Target SNR, $+5\\to-5$~dB (%s)' % m['SnrCommonCount'],
         pct(m['SnrRankFailHigh']), pct(m['SnrRankFailLow']),
         sign(m['SnrRankFailDelta']), ci(m['SnrRankFailDeltaCI'])),
        ('\\quad same, RMS-matched views',
         pct(m['RmsRankFailHigh']), pct(m['RmsRankFailLow']),
         sign(m['RmsRankFailDelta']), ci(m['RmsRankFailDeltaCI'])),
        ('Distractors, $1\\to2$ (%s)' % m['DistCommonCount'],
         pct(m['DistRankFailOneC']), pct(m['DistRankFailTwoC']),
         sign(m['DistRankFailDelta']), ci(m['DistRankFailDeltaCI'])),
        ('\\quad same, one randomly kept rival',
         pct(m['DistRankFailOneC']), pct(m['DistRankFailTwoSingleRival']),
         sign(m['DistRankFailSingleRivalDelta']), ci(m['DistRankFailSingleRivalDeltaCI'])),
        ('\\multicolumn{5}{l}{\\emph{Training (Qwen2.5-Omni-7B $\\to$ +AHA, common-correct)}}\\\\',),
        ('Ranking-failure share',
         pct(m['BaseCCRankFail']), pct(m['AHACCRankFail']),
         sign(m['AHACCDeltaRankFail']), ci(m['AHACCDeltaRankFailCI'])),
    ]
    with open(OUT_TAB, 'w') as f:
        f.write('% Generated by scripts/make_contrast_table.py\n')
        f.write('\\begin{tabular}{lrrrr}\n\\toprule\n')
        f.write('Contrast & A & B & $\\Delta$ & 95\\% CI \\\\\n\\midrule\n')
        for r in rows:
            if len(r) == 1:
                f.write(r[0] + '\n')
            else:
                f.write(' & '.join(r) + ' \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')

    d = json.load(open(INP))
    rec = next(r for r in d['panels']['baseline']
               if r['model_id'] == CASE_MODEL and r['condition_id'] == CASE_COND)
    cats = {}
    for r in d['panels']['baseline']:
        if r['source_tuple_id'] == rec['source_tuple_id']:
            cats[r['target_index']] = r['target_category']
    rival = cats[rec['off_indices'][0]]
    snr = rec['snr_db']
    snr_s = ('%+d' % snr) if snr != 0 else '0'
    with open(OUT_CASE, 'w') as f:
        f.write('% Generated by scripts/make_contrast_table.py\n')
        f.write('\\newcommand{\\ExModel}{%s}\n' % CASE_MODEL_NAME)
        f.write('\\newcommand{\\ExTarget}{%s}\n' % rec['target_category'])
        f.write('\\newcommand{\\ExRival}{%s}\n' % rival)
        f.write('\\newcommand{\\ExSnr}{%s}\n' % snr_s)
        f.write('\\newcommand{\\ExOverlap}{%s}\n' % rec['overlap'])
        f.write('\\newcommand{\\ExMf}{%s}\n' % num(rec['mf'], 1))
        f.write('\\newcommand{\\ExMt}{%s}\n' % num(rec['mt'], 1))
        f.write('\\newcommand{\\ExMj}{%s}\n' % num(rec['mj'][0], 2))
        # Derived effects, so the caption cannot drift from the scored margins.
        # ExDt is the target-removal effect (target-only check), ExDj the
        # rival-removal effect that exceeds it.
        f.write('\\newcommand{\\ExDt}{%s}\n' % num(rec['mf'] - rec['mt'], 2))
        f.write('\\newcommand{\\ExDj}{%s}\n' % num(rec['mf'] - rec['mj'][0], 2))
    print(open(OUT_TAB).read())
    print(open(OUT_CASE).read())


def format_table1():
    """Emit Table 1 without best/worst marks.

    Every column except Acc. is conditioned on that model's own correct
    answers, so a per-column extremum would compare different answer subsets.
    The caption states this; marks are omitted rather than implied.
    """
    lines = open(TAB1).read().splitlines()
    body = [l for l in lines if l.endswith('\\\\') and not l.startswith('Model') and not l.startswith('Pooled')]
    cells = [[c.strip() for c in l[:-2].split('&')] for l in body]
    vals = [[float(c) for c in r[1:]] for r in cells]
    out = []
    bi = 0
    for l in lines:
        if l in body:
            r = cells[bi]; v = vals[bi]; bi += 1
            fmt = [r[0]] + [f'{x:.1f}' for x in v]
            out.append(' & '.join(fmt) + ' \\\\')
        else:
            out.append(l)
    with open(OUT_TAB1, 'w') as f:
        f.write('% Generated by scripts/make_contrast_table.py from attribution_table.tex\n')
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
    format_table1()
