#!/usr/bin/env python3
"""Compose the single risk-quintile table for Sec. 5.2.

The paper previously reported the quintile structure (Table 3) and the
target-substitution experiment (Table 4) as two separate floats, each with its
own caption, and the per-model substitution panel in full. They answer one
question -- how the Q1-versus-Q5 failure gap behaves when the panel is
re-paired or when the target recordings are replaced -- so they are reported
here as one compact table, and the per-model evidence is stated in the prose
from its macros rather than printed as eight rows.

Every entry is read from generated/category_structure.json and
generated/subst_results.json, never recomputed here, and each printed value is
asserted equal to the published macro so the table and the prose cannot drift
apart silently.

Writes generated/risk_table.tex.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / 'generated'
CAT = json.loads((GEN / 'category_structure.json').read_text())
SUB = json.loads((GEN / 'subst_results.json').read_text())
M = dict(re.findall(r'\\newcommand\{\\(\w+)\}\{(.*)\}',
                    (GEN / 'category_structure.tex').read_text()
                    + (GEN / 'subst_numbers.tex').read_text()))


def main():
    # Quintiles are defined on the main panel; the same Q1 and Q5 role sets are
    # re-scored on the re-paired panel and re-rendered in the target control.
    # The re-paired panel is scored on all five frozen quintiles, but the
    # target control fixes its roles at the two extremes, so its middle
    # quintiles do not exist and are left blank rather than filled in.
    main_q = [q['rf'] for q in CAT['frozen']]
    rep_q = [q['rf'] for q in CAT['repair']]

    rows = [
        ('Main (frozen targets)', main_q, 'CatQW', 'CatGap'),
        ('\\quad re-paired backgrounds', rep_q, 'CatQR', 'CatRepGap'),
        ('\\quad targets frozen', [SUB['q1_frozen'], None, None, None,
                                   SUB['q5_frozen']], 'SubstQ{OS}', 'SubstGapFrozen'),
        ('\\quad targets replaced', [SUB['q1_subst'], None, None, None,
                                     SUB['q5_subst']], 'SubstQ{OS}', 'SubstGapSubst'),
    ]

    lines = ['% Generated by scripts/make_risk_table.py',
             '\\begin{tabular}{lrrrrrr}', '\\toprule',
             'Panel & Q1 & Q2 & Q3 & Q4 & Q5 & Gap \\\\', '\\midrule']
    for name, qs, mpat, mg in rows:
        cells = []
        for k, v in enumerate(qs, 1):
            if v is None:
                cells.append('--')
                continue
            # Macro naming differs between the two panels: the main and
            # re-paired panels key by rank (\CatQWOne), the target control by
            # which arm it is (\SubstQOneFrozen).
            if mpat == 'SubstQ{OS}':
                key = ('SubstQOneFrozen' if k == 1 else 'SubstQFiveFrozen'
                       if k == 5 else None) if mg == 'SubstGapFrozen' else (
                      'SubstQOneSubst' if k == 1 else 'SubstQFiveSubst'
                      if k == 5 else None)
            else:
                key = f'{mpat}{("One","Two","Three","Four","Five")[k-1]}'
            assert key is not None, f'{name}: no macro for quintile {k}'
            want = f'{v:.1f}\\%'
            assert M[key] == want, f'{key}: macro {M[key]!r} != row {want!r}'
            cells.append(f'{v:.1f}')
        gap = qs[0] - qs[-1]
        assert M[mg] == f'{gap:+.1f}', f'{mg}: {M[mg]!r} != {gap:+.1f}'
        lines.append(f'{name} & ' + ' & '.join(cells) + f' & ${gap:+.1f}$ \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']

    # The two panels behind the rows above must be the ones the prose cites.
    assert abs(CAT['gap'] - (main_q[0] - main_q[-1])) < 1e-9, 'CatGap mismatch'
    assert abs(CAT['repair_gap'] - (rep_q[0] - rep_q[-1])) < 1e-9, 'CatRepGap mismatch'

    (GEN / 'risk_table.tex').write_text('\n'.join(lines) + '\n')
    print('wrote generated/risk_table.tex')
    for name, qs, _, _ in rows:
        cells = ' '.join('  --' if v is None else f'{v:5.1f}' for v in qs)
        print(f'  {name:26s}{cells}  {qs[0]-qs[-1]:+6.1f}')


if __name__ == '__main__':
    main()
