"""Build generated/attribution_checks.tex: the overlap decomposition of
counterfactual checks on the same correct mixture answers.

All rows are computed from the same correct mixture answers in
generated/counterfactual_inputs.json using the canonical `prepare()`
from build_attribution_numbers, so every column is comparable and cannot
drift from the numbers quoted elsewhere in the paper.

The table is a set decomposition, not a performance ranking. Every
denominator is the same set of correct answers, and for each check the
three columns partition its own alarm set:

  Flagged   = share of the correct answers the check alarms on
  Conflict  = share that both alarm and carry an ordering conflict (H <= 0)
  Separable = share that alarm while the ordering is still locally
              separable (H > 0), i.e. the absent view is still called
              present although some shared threshold orders the views

  target-only score   alarms when dt <= 0
  target-removed answer alarms when mt > 0
  answer flip         alarms when mt > 0 or some mj <= 0
  ordering test       alarms when H <= 0   (TRACE)

For the target-only score and ordering rows the `Conflict` column equals
`Flagged` by construction, because dt <= 0 implies H <= 0 and the ordering
row is defined by H <= 0; those two rows therefore report a set identity
rather than an empirical detection rate. `Separable` is the column that
matters here: it is where answer-level checks flag an answer that a shared
local threshold still orders correctly.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
GEN = HERE.parent / 'generated'

from build_attribution_numbers import load  # noqa: E402


def build():
    _, us, _ = load()
    correct = [u for u in us if u['correct']]
    n_correct = len(correct)
    tot_fail = sum(1 for u in correct if u['H'] <= 0)

    def counts(pred):
        f = [u for u in correct if pred(u)]
        nf = len(f)
        nc = sum(1 for u in f if u['H'] <= 0)
        return nf, nc

    rows = [
        ('Target-only score', counts(lambda u: u['dt'] <= 0)),
        ('Target-removed answer', counts(lambda u: u['mt'] > 0)),
        ('Answer flip', counts(lambda u: u['flip_fail'])),
        (r'\method{} (ordering)', counts(lambda u: u['H'] <= 0)),
    ]

    lines = ['% Generated by scripts/make_checks_table.py',
             r'\begin{tabular}{lrrr}', r'\toprule',
             r'Check & Flagged & Conflict & Separable \\', r'\midrule']
    for name, (nf, nc) in rows:
        fl = 100.0 * nf / n_correct
        co = 100.0 * nc / n_correct
        sep = 100.0 * (nf - nc) / n_correct
        lines.append(f'{name} & {fl:.1f} & {co:.1f} & {sep:.1f} \\\\')
    lines += [r'\bottomrule', r'\end{tabular}', '']
    (GEN / 'attribution_checks.tex').write_text('\n'.join(lines))

    print(f'n_correct={n_correct:,}  ordering conflicts (H<=0)={tot_fail:,} '
          f'({100*tot_fail/n_correct:.2f}%)')
    for name, (nf, nc) in rows:
        print(f'  {name:24s} flagged={nf:6,} ({100*nf/n_correct:5.1f}%)  '
              f'conflict={nc:6,} ({100*nc/n_correct:5.1f}%)  '
              f'separable={nf-nc:6,} ({100*(nf-nc)/n_correct:5.1f}%)')


if __name__ == '__main__':
    build()
